# Generated by Django 2.0.5 on 2018-06-03 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_race_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='ability_bonus',
            field=models.TextField(default=''),
        ),
    ]
