# Generated by Django 2.0.6 on 2018-06-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_race_ability_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='prd_url',
            field=models.URLField(default=''),
        ),
    ]
